<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (! Item::exists()) {
            // Item::factory(10)->notOnSale()->create();
            Item::insert([
                [
                    'name' => '腕時計',
                    'price' => 15000,
                    'description' => 'スタイリッシュなデザインのメンズ腕時計',
                    'image' => 'Armani_Mens_Clock.jpg',
                    'condition_id' => 1,
                    'seller_id' => 1,
                    'on_sale' => 0,
                    'brand' => 'アルマーニ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HDD',
                    'price' => 5000,
                    'description' => '高速で信頼性の高いハードディスク',
                    'image' => 'HDD_Hard_Disk.jpg',
                    'condition_id' => 2,
                    'seller_id' => 2,
                    'on_sale' => 0,
                    'brand' => '日田日立',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '玉ねぎ3束',
                    'price' => 300,
                    'description' => '新鮮な玉ねぎ3束のセット',
                    'image' => 'iLoveIMG_d.jpg',
                    'condition_id' => 3,
                    'seller_id' => 3,
                    'on_sale' => 1,
                    'brand' => '春日井農園',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '革靴',
                    'price' => 4000,
                    'description' => 'クラシックなデザインの革靴',
                    'image' => 'Leather_Shoes_Product_Photo.jpg',
                    'condition_id' => 4,
                    'seller_id' => 4,
                    'on_sale' => 1,
                    'brand' => '牛の皮',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ノートPC',
                    'price' => 45000,
                    'description' => '高性能なノートパソコン',
                    'image' => 'Living_Room_Laptop.jpg',
                    'condition_id' => 1,
                    'seller_id' => 5,
                    'on_sale' => 1,
                    'brand' => 'NEEC',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'マイク',
                    'price' => 8000,
                    'description' => '高音質のレコーディング用マイク',
                    'image' => 'Music_Mic_4632231.jpg',
                    'condition_id' => 2,
                    'seller_id' => 1,
                    'on_sale' => 0,
                    'brand' => 'マイクロマイク',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ショルダーバッグ',
                    'price' => 3500,
                    'description' => 'おしゃれなショルダーバッグ',
                    'image' => 'Purse_fashion_pocket.jpg',
                    'condition_id' => 3,
                    'seller_id' => 2,
                    'on_sale' => 0,
                    'brand' => 'ぐっちっち',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'タンブラー',
                    'price' => 500,
                    'description' => '使いやすいタンブラー',
                    'image' => 'Tumbler_souvenir.jpg',
                    'condition_id' => 4,
                    'seller_id' => 3,
                    'on_sale' => 1,
                    'brand' => '金属探知機',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'コーヒーミル',
                    'price' => 4000,
                    'description' => '手動のコーヒーミル',
                    'image' => 'Waitress_with_Coffee_Grinder.jpg',
                    'condition_id' => 1,
                    'seller_id' => 4,
                    'on_sale' => 1,
                    'brand' => '久保田',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'メイクセット',
                    'price' => 2500,
                    'description' => '便利なメイクアップセット',
                    'image' => 'makeup_set.jpg',
                    'condition_id' => 2,
                    'seller_id' => 5,
                    'on_sale' => 1,
                    'brand' => '魚油産業',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '腕時計',
                    'price' => 15000,
                    'description' => 'スタイリッシュなデザインのメンズ腕時計',
                    'image' => 'Armani_Mens_Clock.jpg',
                    'condition_id' => 1,
                    'seller_id' => 1,
                    'on_sale' => 1,
                    'brand' => 'アルマーニ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HDD',
                    'price' => 5000,
                    'description' => '高速で信頼性の高いハードディスク',
                    'image' => 'HDD_Hard_Disk.jpg',
                    'condition_id' => 2,
                    'seller_id' => 2,
                    'on_sale' => 1,
                    'brand' => '日田日立',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '玉ねぎ3束',
                    'price' => 300,
                    'description' => '新鮮な玉ねぎ3束のセット',
                    'image' => 'iLoveIMG_d.jpg',
                    'condition_id' => 3,
                    'seller_id' => 3,
                    'on_sale' => 1,
                    'brand' => '春日井農園',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '革靴',
                    'price' => 4000,
                    'description' => 'クラシックなデザインの革靴',
                    'image' => 'Leather_Shoes_Product_Photo.jpg',
                    'condition_id' => 4,
                    'seller_id' => 4,
                    'on_sale' => 1,
                    'brand' => '牛の皮',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ノートPC',
                    'price' => 45000,
                    'description' => '高性能なノートパソコン',
                    'image' => 'Living_Room_Laptop.jpg',
                    'condition_id' => 1,
                    'seller_id' => 5,
                    'on_sale' => 1,
                    'brand' => 'NEEC',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'マイク',
                    'price' => 8000,
                    'description' => '高音質のレコーディング用マイク',
                    'image' => 'Music_Mic_4632231.jpg',
                    'condition_id' => 2,
                    'seller_id' => 6,
                    'on_sale' => 1,
                    'brand' => 'マイクロマイク',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ショルダーバッグ',
                    'price' => 3500,
                    'description' => 'おしゃれなショルダーバッグ',
                    'image' => 'Purse_fashion_pocket.jpg',
                    'condition_id' => 3,
                    'seller_id' => 7,
                    'on_sale' => 1,
                    'brand' => 'ぐっちっち',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'タンブラー',
                    'price' => 500,
                    'description' => '使いやすいタンブラー',
                    'image' => 'Tumbler_souvenir.jpg',
                    'condition_id' => 4,
                    'seller_id' => 8,
                    'on_sale' => 1,
                    'brand' => '金属探知機',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'コーヒーミル',
                    'price' => 4000,
                    'description' => '手動のコーヒーミル',
                    'image' => 'Waitress_with_Coffee_Grinder.jpg',
                    'condition_id' => 1,
                    'seller_id' => 9,
                    'on_sale' => 1,
                    'brand' => '久保田',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'メイクセット',
                    'price' => 2500,
                    'description' => '便利なメイクアップセット',
                    'image' => 'makeup_set.jpg',
                    'condition_id' => 2,
                    'seller_id' => 10,
                    'on_sale' => 1,
                    'brand' => '魚油産業',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                                [
                    'name' => '腕時計',
                    'price' => 15000,
                    'description' => 'スタイリッシュなデザインのメンズ腕時計',
                    'image' => 'Armani_Mens_Clock.jpg',
                    'condition_id' => 1,
                    'seller_id' => 1,
                    'on_sale' => 1,
                    'brand' => 'アルマーニ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HDD',
                    'price' => 5000,
                    'description' => '高速で信頼性の高いハードディスク',
                    'image' => 'HDD_Hard_Disk.jpg',
                    'condition_id' => 2,
                    'seller_id' => 2,
                    'on_sale' => 1,
                    'brand' => '日田日立',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '玉ねぎ3束',
                    'price' => 300,
                    'description' => '新鮮な玉ねぎ3束のセット',
                    'image' => 'iLoveIMG_d.jpg',
                    'condition_id' => 3,
                    'seller_id' => 3,
                    'on_sale' => 1,
                    'brand' => '春日井農園',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '革靴',
                    'price' => 4000,
                    'description' => 'クラシックなデザインの革靴',
                    'image' => 'Leather_Shoes_Product_Photo.jpg',
                    'condition_id' => 4,
                    'seller_id' => 4,
                    'on_sale' => 1,
                    'brand' => '牛の皮',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ノートPC',
                    'price' => 45000,
                    'description' => '高性能なノートパソコン',
                    'image' => 'Living_Room_Laptop.jpg',
                    'condition_id' => 1,
                    'seller_id' => 5,
                    'on_sale' => 1,
                    'brand' => 'NEEC',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'マイク',
                    'price' => 8000,
                    'description' => '高音質のレコーディング用マイク',
                    'image' => 'Music_Mic_4632231.jpg',
                    'condition_id' => 2,
                    'seller_id' => 6,
                    'on_sale' => 1,
                    'brand' => 'マイクロマイク',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ショルダーバッグ',
                    'price' => 3500,
                    'description' => 'おしゃれなショルダーバッグ',
                    'image' => 'Purse_fashion_pocket.jpg',
                    'condition_id' => 3,
                    'seller_id' => 7,
                    'on_sale' => 1,
                    'brand' => 'ぐっちっち',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'タンブラー',
                    'price' => 500,
                    'description' => '使いやすいタンブラー',
                    'image' => 'Tumbler_souvenir.jpg',
                    'condition_id' => 4,
                    'seller_id' => 8,
                    'on_sale' => 1,
                    'brand' => '金属探知機',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'コーヒーミル',
                    'price' => 4000,
                    'description' => '手動のコーヒーミル',
                    'image' => 'Waitress_with_Coffee_Grinder.jpg',
                    'condition_id' => 1,
                    'seller_id' => 9,
                    'on_sale' => 1,
                    'brand' => '久保田',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'メイクセット',
                    'price' => 2500,
                    'description' => '便利なメイクアップセット',
                    'image' => 'makeup_set.jpg',
                    'condition_id' => 2,
                    'seller_id' => 10,
                    'on_sale' => 1,
                    'brand' => '魚油産業',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                                [
                    'name' => '腕時計',
                    'price' => 15000,
                    'description' => 'スタイリッシュなデザインのメンズ腕時計',
                    'image' => 'Armani_Mens_Clock.jpg',
                    'condition_id' => 1,
                    'seller_id' => 1,
                    'on_sale' => 1,
                    'brand' => 'アルマーニ',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HDD',
                    'price' => 5000,
                    'description' => '高速で信頼性の高いハードディスク',
                    'image' => 'HDD_Hard_Disk.jpg',
                    'condition_id' => 2,
                    'seller_id' => 2,
                    'on_sale' => 1,
                    'brand' => '日田日立',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '玉ねぎ3束',
                    'price' => 300,
                    'description' => '新鮮な玉ねぎ3束のセット',
                    'image' => 'iLoveIMG_d.jpg',
                    'condition_id' => 3,
                    'seller_id' => 3,
                    'on_sale' => 1,
                    'brand' => '春日井農園',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => '革靴',
                    'price' => 4000,
                    'description' => 'クラシックなデザインの革靴',
                    'image' => 'Leather_Shoes_Product_Photo.jpg',
                    'condition_id' => 4,
                    'seller_id' => 4,
                    'on_sale' => 1,
                    'brand' => '牛の皮',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ノートPC',
                    'price' => 45000,
                    'description' => '高性能なノートパソコン',
                    'image' => 'Living_Room_Laptop.jpg',
                    'condition_id' => 1,
                    'seller_id' => 5,
                    'on_sale' => 1,
                    'brand' => 'NEEC',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'マイク',
                    'price' => 8000,
                    'description' => '高音質のレコーディング用マイク',
                    'image' => 'Music_Mic_4632231.jpg',
                    'condition_id' => 2,
                    'seller_id' => 6,
                    'on_sale' => 1,
                    'brand' => 'マイクロマイク',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ショルダーバッグ',
                    'price' => 3500,
                    'description' => 'おしゃれなショルダーバッグ',
                    'image' => 'Purse_fashion_pocket.jpg',
                    'condition_id' => 3,
                    'seller_id' => 7,
                    'on_sale' => 1,
                    'brand' => 'ぐっちっち',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'タンブラー',
                    'price' => 500,
                    'description' => '使いやすいタンブラー',
                    'image' => 'Tumbler_souvenir.jpg',
                    'condition_id' => 4,
                    'seller_id' => 8,
                    'on_sale' => 1,
                    'brand' => '金属探知機',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'コーヒーミル',
                    'price' => 4000,
                    'description' => '手動のコーヒーミル',
                    'image' => 'Waitress_with_Coffee_Grinder.jpg',
                    'condition_id' => 1,
                    'seller_id' => 9,
                    'on_sale' => 1,
                    'brand' => '久保田',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'メイクセット',
                    'price' => 2500,
                    'description' => '便利なメイクアップセット',
                    'image' => 'makeup_set.jpg',
                    'condition_id' => 2,
                    'seller_id' => 10,
                    'on_sale' => 1,
                    'brand' => '魚油産業',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
          }
    }
}
